'use client';

import { motion, useScroll, useTransform } from 'framer-motion';
import { useRef, useState, useEffect } from 'react';
import { Scale, ShieldAlert, Cpu, Zap, Ban, AlertOctagon, BookOpen } from 'lucide-react';
import { Space_Grotesk, Exo_2 } from 'next/font/google';

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] });
const exo2 = Exo_2({ subsets: ['latin'] });

const SECTIONS = [
  {
    id: 'acceptance',
    title: 'Acceptance of Terms',
    icon: BookOpen,
    description: 'By accessing the OVIC Labs enterprise platform, leasing our autonomous hardware, or utilizing our software APIs, you agree to be bound by these Terms of Service. These terms constitute a legally binding agreement between you and OVIC Labs, governing all interactions with our AI models and physical robotics ecosystems.',
    bullets: []
  },
  {
    id: 'provision',
    title: 'Provision of Robotics Services',
    icon: Cpu,
    description: 'OVIC Labs provides cutting-edge, experimental, and enterprise-grade robotic hardware and software. The provision of these services is subject to strict operational guidelines.',
    bullets: [
      <><strong>Hardware Deployment:</strong> Autonomous units remain the exclusive property of OVIC Labs unless explicitly purchased under a separate hardware acquisition agreement. Clients are granted a limited license to operate the units within approved geofenced zones.</>,
      <><strong>Beta Software & Firmwares:</strong> We continuously deploy over-the-air (OTA) updates. Certain features may be designated as "Beta" and are provided "as-is" without warranty of continuous operation.</>,
      <><strong>Operational Autonomy:</strong> OVIC Labs reserves the right to remotely ground, disable, or recall any active robotics unit if telemetry indicates a critical safety malfunction or unauthorized geographic deviation.</>
    ]
  },
  {
    id: 'acceptable-use',
    title: 'Acceptable Use Policy',
    icon: Ban,
    description: 'The physical and digital integrity of our systems is paramount. You agree not to engage in any prohibited uses of our technology.',
    bullets: [
      <><strong>No Weaponization:</strong> Under no circumstances may any OVIC Labs hardware or software be modified, weaponized, or utilized for military combat operations, surveillance of unconsenting civilians, or law enforcement hostile actions.</>,
      <><strong>Interference & Tampering:</strong> Intentional blinding of LiDAR sensors, physical obstruction of delivery routes, or reverse engineering of the secure enclave (TPM) is strictly prohibited and grounds for immediate termination.</>,
      <><strong>AI Model Abuse:</strong> Submitting malicious prompts or attempting to extract proprietary weights from our localized natural language models violates our core intellectual property guidelines.</>
    ]
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual Property & AI Models',
    icon: Zap,
    description: 'OVIC Labs respects client data ownership while vigorously protecting our foundational AI models and hardware designs.',
    bullets: [
      <><strong>Model Weights:</strong> All neural network architectures, pre-trained weights, and continuous learning algorithms remain the exclusive intellectual property of OVIC Labs.</>,
      <><strong>Client Data:</strong> Data generated by your specific enterprise use-case (e.g., your warehouse inventory data) belongs to you. However, you grant OVIC Labs a perpetual license to use anonymized telemetry to improve generalized robotic navigation.</>,
      <><strong>Hardware Designs:</strong> The physical schematics, chassis designs, and actuator configurations are protected by international patent laws. Unauthorized replication is strictly prohibited.</>
    ]
  },
  {
    id: 'liability',
    title: 'Liability and Safety Disclaimers',
    icon: ShieldAlert,
    description: 'Interacting with heavy, autonomous machinery carries inherent risks. We require all partners to acknowledge the unpredictable nature of real-world AI.',
    bullets: [
      <><strong>Experimental Nature:</strong> While our systems undergo rigorous safety testing, autonomous navigation in unstructured environments (public sidewalks, mixed-use warehouses) is inherently probabilistic.</>,
      <><strong>Limitation of Liability:</strong> To the maximum extent permitted by law, OVIC Labs shall not be liable for any indirect, incidental, or consequential damages arising from the operation, malfunction, or routing errors of our robotic fleets.</>,
      <><strong>Client Indemnification:</strong> You agree to indemnify OVIC Labs against claims arising from your employees intentionally disregarding published safety protocols while interacting with the robots.</>
    ]
  },
  {
    id: 'termination',
    title: 'Termination of Services',
    icon: AlertOctagon,
    description: 'OVIC Labs maintains the right to protect its fleet and network integrity through service termination.',
    bullets: [
      <><strong>Immediate Suspension:</strong> We may instantly suspend API access and remotely disable hardware if we detect a breach of the Acceptable Use Policy or a critical security compromise on the client network.</>,
      <><strong>Hardware Retrieval:</strong> Upon termination of a leasing agreement, clients must secure all robotic units in a safe loading area for OVIC Labs retrieval teams within 48 hours.</>
    ]
  },
  {
    id: 'governing-law',
    title: 'Governing Law & Dispute Resolution',
    icon: Scale,
    description: 'These Terms of Service are governed by the laws of the State of California, without regard to its conflict of law principles.',
    bullets: [
      <><strong>Binding Arbitration:</strong> Any disputes arising out of these terms or the use of OVIC Labs hardware shall be resolved through binding arbitration in San Francisco, California.</>,
      <><strong>Class Action Waiver:</strong> You agree to bring claims against OVIC Labs only in your individual capacity, and not as a plaintiff or class member in any purported class or representative proceeding.</>
    ]
  }
];

function PolicyCard({ title, description, bullets, icon: Icon, id, index }: any) {
  return (
    <motion.div
      id={id}
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.6, delay: index * 0.05 }}
      className="relative w-full mb-12"
    >
      <div className="bg-white border border-neutral-200 p-6 sm:p-8 md:p-10 rounded-2xl shadow-sm hover:shadow-md transition-shadow duration-300">
        <div className="flex flex-col sm:flex-row items-start gap-4 sm:gap-6">
          <div className="w-10 h-10 md:w-12 md:h-12 rounded-xl bg-neutral-100 flex items-center justify-center shrink-0 text-neutral-800">
            <Icon size={20} className="md:w-[22px] md:h-[22px]" />
          </div>
          <div className="flex-1">
            <h3 className="text-xl md:text-2xl font-bold text-neutral-900 mb-3 md:mb-4">{title}</h3>
            <p className="text-neutral-600 leading-relaxed text-sm md:text-[15px] mb-4">
              {description}
            </p>
            {bullets && bullets.length > 0 && (
              <div className="space-y-4 mt-6">
                {bullets.map((bullet: any, i: number) => (
                  <div key={i} className="flex items-start group/bullet">
                    <div className="w-5 h-5 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center shrink-0 mt-0.5 mr-4 border border-blue-100 transition-colors group-hover/bullet:bg-blue-100 group-hover/bullet:border-blue-200">
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-600" />
                    </div>
                    <div className="text-neutral-600 text-sm md:text-[15px] leading-relaxed">
                      {bullet}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </motion.div>
  );
}

export default function TermsOfService() {
  const containerRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: containerRef, offset: ["start start", "end end"] });
  const [activeSection, setActiveSection] = useState(SECTIONS[0].id);

  const y1 = useTransform(scrollYProgress, [0, 1], [0, -100]);

  useEffect(() => {
    const handleScroll = () => {
      const sections = SECTIONS.map(s => document.getElementById(s.id));
      const scrollPosition = window.scrollY + window.innerHeight / 3;
      
      for (let i = sections.length - 1; i >= 0; i--) {
        const section = sections[i];
        if (section && section.offsetTop <= scrollPosition) {
          setActiveSection(SECTIONS[i].id);
          break;
        }
      }
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollTo = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      window.scrollTo({
        top: element.offsetTop - 120,
        behavior: 'smooth'
      });
    }
  };

  return (
    <div ref={containerRef} className={`min-h-screen bg-transparent relative ${spaceGrotesk.className}`}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 md:py-12 relative z-10">
        {/* Hero Section */}
        <motion.div 
          style={{ y: y1 }}
          className="mb-12 md:mb-20 max-w-3xl"
        >
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className={`text-3xl sm:text-4xl md:text-6xl font-bold tracking-tight text-neutral-900 mb-4 md:mb-6 ${exo2.className}`}
          >
            Terms of Service
          </motion.h1>
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="flex flex-col sm:flex-row sm:items-center gap-1.5 sm:gap-4 text-xs sm:text-sm text-neutral-500 font-medium mt-2"
          >
            <p>Effective Date: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
            <span className="hidden sm:inline">•</span>
            <p>Version: 1.4.0</p>
          </motion.div>
        </motion.div>

        <div className="flex flex-col lg:flex-row gap-16 relative">
          {/* Sticky Sidebar */}
          <div className="hidden lg:block w-72 shrink-0">
            <div className="sticky top-32">
              <motion.div 
                initial={{ opacity: 0, x: -30 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6 }}
                className="bg-white border border-neutral-200 p-6 rounded-2xl shadow-sm"
              >
                <h4 className="text-xs font-bold uppercase tracking-widest text-neutral-400 mb-6 px-4">Contents</h4>
                <nav className="flex flex-col gap-1">
                  {SECTIONS.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => scrollTo(section.id)}
                      className={`flex items-center justify-between px-4 py-2.5 rounded-lg transition-colors text-left text-sm font-medium ${
                        activeSection === section.id 
                          ? 'bg-neutral-100 text-neutral-900' 
                          : 'text-neutral-500 hover:bg-neutral-50 hover:text-neutral-900'
                      }`}
                    >
                      <span className="truncate pr-4">{section.title}</span>
                      {activeSection === section.id && (
                        <motion.div layoutId="activeMarker" className="w-1.5 h-1.5 rounded-full bg-neutral-900 shrink-0" />
                      )}
                    </button>
                  ))}
                </nav>
              </motion.div>
            </div>
          </div>

          {/* Main Content Sections */}
          <div className="flex-1 max-w-3xl">
            <motion.p 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="text-base md:text-lg leading-relaxed text-neutral-700 mb-10 md:mb-12 border-l-[3px] md:border-l-4 border-neutral-300 pl-4 md:pl-6"
            >
              Welcome to <strong>OVIC Labs</strong>. These Terms of Service regulate your use of our physical robotic platforms, cloud APIs, and enterprise management software. Due to the physical nature of our autonomous hardware, strict adherence to these operational terms is required to ensure the safety of all parties.
            </motion.p>

            <div className="space-y-4">
              {SECTIONS.map((section, index) => (
                <PolicyCard 
                  key={section.id} 
                  id={section.id}
                  title={section.title} 
                  description={section.description}
                  bullets={section.bullets}
                  icon={section.icon} 
                  index={index}
                />
              ))}
            </div>

            {/* Corporate Contact Block */}
            <motion.div 
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="mt-12 md:mt-16 bg-neutral-900 text-white p-6 sm:p-8 md:p-10 rounded-2xl"
            >
              <h3 className="text-xl md:text-2xl font-bold mb-3 md:mb-4">Legal Correspondence</h3>
              <p className="text-neutral-400 leading-relaxed text-sm md:text-base mb-6 md:mb-8">
                For inquiries regarding these Terms of Service, licensing agreements, or to report a violation of our Acceptable Use Policy, please contact our legal department.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-6 sm:gap-12">
                <div>
                  <p className="text-xs font-bold uppercase tracking-widest text-neutral-500 mb-2">Team</p>
                  <p className="font-medium">General Counsel</p>
                  <a href="mailto:legal@oviclabs.com" className="text-neutral-300 hover:text-white transition-colors">legal@oviclabs.com</a>
                </div>

              </div>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
